info:
  name: item_2
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{API_URL}}/item"
  body:
    type: json
    data: |-
      {
           "itemid": "104.342.001"
             
       }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
